site_name: 数学分享站
site_url: https://courseshare.github.io
repo_url: https://github.com/courseshare/courseshare.github.io
repo_name: courseshare
copyright: Copyright © 2024 [courseshare]

theme:
  name: material
  custom_dir: overrides
  language: zh

  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
    - scheme: default    # Palette toggle for light mode
      toggle:
        icon: material/brightness-7 
        name: 启动暗影模式

    - scheme: slate    # Palette toggle for dark mode
      toggle:
        icon: material/brightness-4
        name: 开启日光模式

  font: 
    text: Noto Sans SC
    code: Roboto Mono

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    annotation: material/arrow-right-circle
  features:
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.instant


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/consent.js

# 扩展css
extra_css:
  - stylesheets/extra.css

# cookie
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      extra:
    actions:
      - accept
      - reject
      - manage




# encrypt
plugins:
    - privacy
    - search: {}
    - encryptcontent:
        password_inventory:
          classified: 'password1'
          confidential:
            - 'password2'
            - 'password3'
          secret:
            keran: 'wajy'
            user5: 'password5'

# 页面
nav:
#  - 首页："index.md"
  - 测试: 'text.md'
  - 函数与导数: 'function.md'

